apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Medelouali/DevOpsCycleGitOps.git
    targetRevision: HEAD
    path: k8s
  destination: 
    server: https://kubernetes.default.svc
    namespace: devops-cycle-test

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true