apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: QmluZ29vWW91R290SXQ=
  MYSQL_ROOT_USERNAME: aU9CdVM5eGtnVTBw
  MYSQL_DATABASE: aU9CdVM5eGtnVTBw
