apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: mysql-service
  MYSQL_ROOT_USERNAME: dmFsdWUtMg0KDQo
  MYSQL_DATABASE: dmFsdWUtMg0KDQo
