apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: beta-release
    meta.helm.sh/release-namespace: helm-test
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: QmluZ29vWW91R290SXQ=
  MYSQL_ROOT_USERNAME: aU9CdVM5eGtnVTBw
  MYSQL_DATABASE: aU9CdVM5eGtnVTBw
